runtime: python27
api_version: 1
threadsafe: true

# Handlers match in order, put above the default handler.
handlers:
- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /.*
  script: hotestprogrammerhumor.app

- url: /grab/
  script: hotestprogrammerhumor.grab
  login: admin

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
